name: Jekyll Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jekyll-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build Jekyll site using Docker
        run: |
          docker run \
          --rm \
          -v "${{ github.workspace }}:/srv/jekyll" \
          -v "${{ github.workspace }}/_site:/srv/jekyll/_site" \
          jekyll/builder:latest \
          jekyll build --future


      - name: Upload Jekyll artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site


  deploy:

    needs: jekyll-build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages


    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
